### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Vaibhavdixit02** [SciML/GlobalSensitivity.jl#15]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register branch=statbasebump

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register branch=statbasebump

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
