### ISSUE TITLE
Argument lists in the documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/GlobalSensitivity.jl#24]
Currently the docs are like:

### API

```julia
function gsa(f, method::eFAST, p_range::AbstractVector; n::Int=1000, batch=false, distributed::Val{SHARED_ARRAY} = Val(false), kwargs...) where {SHARED_ARRAY}
```

But this is missing the argument list, i.e.:

https://diffeq.sciml.ai/stable/types/ode_types/#Constructors

**Comment by ChrisRackauckas** [comment]
The Sobol page should definitely be documenting what a "Design Matrix" is (maybe as a whole section), how it's laid out, etc. with a recommendation to QuasiMonteCarlo.jl as a way to generate them. Right now that's only mentioned in the tutorial.

**Comment by Vaibhavdixit02** [comment]
Should be good now
