### ISSUE TITLE
Sum of Sobol indices in the case of orthogonal inputs

### ISSUE THREAD

**Issue by moesphere** [SciML/GlobalSensitivity.jl#46]
In the case of orthogonal inputs, the sum over all Sobol indices should be equal to 1. Currently, this is not the case.
MWE, where the second-order Sobol indices already exceed 1 considerably:
```julia
using GlobalSensitivity, QuasiMonteCarlo

function ishi(X)
    A= 7
    B= 0.1
    sin(X[1]) + A*sin(X[2])^2+ B*X[3]^4 *sin(X[1])
end

n = 600000
lb = -ones(4)*π
ub = ones(4)*π
sampler = SobolSample()
A,B = QuasiMonteCarlo.generate_design_matrices(n,lb,ub,sampler)

res1 = gsa(ishi,Sobol(order=[0,1,2]),A,B)
```

For a more thorough discussion, see [this thread](https://discourse.julialang.org/t/how-to-interpret-2nd-order-sobol-global-sensitivity-analysis-result/47804) on julia discourse.

**Comment by moesphere** [comment]
From Saltelli, "Sensitivity analysis in practice: a guide to assessing scientific models":

![grafik](https://user-images.githubusercontent.com/19595387/146159020-d72505f9-6046-4051-88e8-07e5dc8f2009.png)

**Comment by Vaibhavdixit02** [comment]
I am not sure what the issue is, as I mentioned in the discourse thread and even you said the same thing https://discourse.julialang.org/t/how-to-interpret-2nd-order-sobol-global-sensitivity-analysis-result/47804/14, if you sum over all the possible orders' indices then only you are guaranteed to get to 1, otherwise it would be "close" to 1, and that is true for the results you get. Please let me know if I am misunderstanding what issue you are seeing?

**Comment by moesphere** [comment]
If you run the MWE from above the Sobol indices are:

![grafik](https://user-images.githubusercontent.com/19595387/146161201-e028ebe2-24c5-4b33-b069-79cf03af1f29.png)

The second order indices, if `res1.S2` are the second order indices, are very much too large. The sum of all of the first and second order indices should not exceed 1.

**Comment by moesphere** [comment]
If you run the same example with the `GlobalSensitivityAnalysis` package, which I also did in the discourse thread, you end up with the following indices:
![grafik](https://user-images.githubusercontent.com/19595387/146161805-94b15edd-45e2-4e3a-9b2c-0aadebb63b54.png)
And they seem to be correct. Note that the sum over all indices does not exceed 1.

**Comment by moesphere** [comment]
Bottomline is that the calculation of the first-order Sobol indices seems to be correct, but not the calculation of the higher-order indices.

**Comment by Vaibhavdixit02** [comment]
Oh I get it now, sorry, I didn't notice GlobalSensitivityAnalysis, I thought they were results from this package. 😅 

Yes this looks incorrect, most probably from some changes we had earlier to the implementation. I'll take a look, thanks for reporting!

**Comment by moesphere** [comment]
Adding the MWE as a test might be a good idea.

**Comment by Vaibhavdixit02** [comment]
Thanks for this important issue @moesphere. It is fixed now in the latest release, please try it out.
