### ISSUE TITLE
eFAST fails when Sobol works. Sobol sum of S1 not always equal to 1.

### ISSUE THREAD

**Issue by Ge0rges** [SciML/GlobalSensitivity.jl#82]
I have a model consisting of a set of differential equations. I would like to conduct a sensitivity analysis on a subset of parameters and get back their sensitivity index. I am using GobalSensitivity.gsa to do this, paired with the Sobol method and a Sobol2007 estimator. I noticed however, that no matter the number of samples, I never get a sum of first order indices equal to 1.0. 

I thought of switching to eFAST as it is supposed to be more efficient, but this method fails completely with the following error:
```
JULIA: ArgumentError: Uniform: the condition a < b is not satisfied.
@ Distributions ~/.julia/packages/Distributions/7iOJp/src/univariate/continuous/uniform.jl:38
@ GlobalSensitivity ~/.julia/packages/GlobalSensitivity/jG1Zc/src/eFAST_sensitivity.jl:98

```

Attached is a file with model outputs for the SA. Below is the code of the model. Note that I multiply all values by 1e200 before SA as they are quite small and this causes issues downstream. This shouldn't affect the result of the SA by my understanding.  Some combinations of parameters do cause the solver to abort a run during the SA (1-4 in every 4000 roughly)

[analysis.txt](https://github.com/SciML/GlobalSensitivity.jl/files/9767181/analysis.txt)

I have also attached the complete model with the set of parameter bounds and initial conditions I use. The model being complex, this is not a minimum-reproducible example. 

```
using DifferentialEquations
using DiffEqSensitivity
using ForwardDiff
using GlobalSensitivity
using Statistics
using Printf

# Define model domain. Reject any values below 0.
function is_invalid_domain(u,p,t)
    return u[1] < 0 || u[2] < 0 || u[3] < 0 || u[4] < 0
end

# Defines a problem object and solves it.
function solve_model(p, u0)
    # Set the time timespan
    tspan = (0.0, last(u0))

    # Build a callback to introduce a carbon addition as it is a discontinuity
    stops = []
    carbon = []
    punctual_organic_carbon_addition = p[end] == -1 ? [] : p[end]
    for (time_to_add, (pOC_to_add, dOC_to_add)) in punctual_organic_carbon_addition
        push!(stops, time_to_add)
        push!(carbon, (convert(Float64, pOC_to_add), convert(Float64, dOC_to_add)))
    end

    additions = Dict(Pair.(stops, carbon))

    addition_condition(u,t,integrator) = any(x->t==x, stops)  # If we hit any of the stops return true
    function addition!(integrator)
        integrator.u[1] += additions[integrator.t][1]
        integrator.u[2] += additions[integrator.t][2]

        if integrator.u[3] < 1
            integrator.u[3] = 1  # Add a viable cell if none exist
        end
    end
    carbon_add_cb = DiscreteCallback(addition_condition, addition!)

    # Convert p and remove puncutal_punctual_organic_carbon_addition
    p = convert(Array{Float64}, p[1:end-1])

    # Build the ODE Problem and Solve
    prob = ODEProblem(model, u0[1:end-1], tspan, p)
    sol = solve(prob, Rosenbrock23(), callback=carbon_add_cb, tstops=stops, isoutofdomain=is_invalid_domain, maxiters=1e7)

    return sol
end


# Runs the sensitivity analysis using Sobol method.
function run_sensitivity_analysis()
    p_bounds = [[1.0e-14, 100000], [0.01, 500], [1, 500], [1000000000, 1000000000], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1.0e-8, 100], [882000.0, 882000.0], [-1, -1]]
    u0 = [1.6382099999999998e13, 3.4061512877350002e10, 0.0, 100000.0, 1.461e7]

    # Define a function that remakes the problem and gets its result
    f1 = function (p)
        sol = solve_model(p, u0)

        # File analysis.txt contains written last(sol[1,:])

        [last(sol[1,:] * 1e200)]  # This hacky solution to handle tiny (10^-300) values sucks.
    end

    # Run GSA
    # fast_result = GlobalSensitivity.gsa(f1, eFAST(), p_bounds, samples=2^14)  # Fails
    sobol_result = GlobalSensitivity.gsa(f1, Sobol(), p_bounds, Ei_estimator=:Sobol2007, samples=2^14)
    return (sobol_result.ST[1,:], sobol_result.S1[1,:])
end


# Implements the differential equations that define the model
function model(du,u,p,t)
    # Paramaters
    mu_max = p[1]
    maintenance_per_cell = p[2]
    dOC_per_cell = p[3]

    carrying_capacity = p[4]
    pOC_input_rate = p[5]
    dOC_input_rate = p[6]
    inorganic_carbon_input_rate = p[7]
    inorganic_carbon_fixing_rate = p[8]
    inorganic_carbon_per_cell = p[9]
    eea_rate = p[10]
    Ks = p[11]

    # Load state conditions
    pOC_content = u[1]
    dOC_content = u[2]
    inorganic_carbon_content = u[3]
    cell_count = u[4]

    growth = mu_max * (dOC_content / (Ks + dOC_content)) * cell_count * (1 - cell_count / carrying_capacity)

    required_dOC_per_cell = maintenance_per_cell
    required_dOC = required_dOC_per_cell * cell_count

    dOC_missing = max(required_dOC - dOC_content, 0)
    starvation_deaths = dOC_missing == 0 ? 0 : dOC_missing / required_dOC_per_cell

    deaths =  starvation_deaths

    dOC_consumption = required_dOC_per_cell * (cell_count - deaths)
    fixed_carbon = inorganic_carbon_fixing_rate * inorganic_carbon_content

    du[1] = pOC_input_rate - eea_rate*pOC_content*cell_count
    du[2] = dOC_input_rate + dOC_per_cell * (deaths - growth) - dOC_consumption + eea_rate*pOC_content*cell_count + fixed_carbon
    du[3] = inorganic_carbon_input_rate + inorganic_carbon_per_cell * (deaths - growth) + required_dOC - fixed_carbon
    du[4] = growth - deaths
end
```

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02 can you look into this one?

**Comment by Vaibhavdixit02** [comment]
> I never get a sum of first order indices equal to 1.0.

The sum of all indices is supposed to be equal 1.0, or the sum of total indices. So, if you looks the sum of total indices in your result, it;s almost 1 (it might not be exactly equal), or else you can compute the second order indices as well by passing `Sobol(order = [0, 1, 2])` and then check the sum of first and second orders together, it should be close to 1.0.

<img width="521" alt="Screenshot 2022-10-17 at 11 45 56 AM" src="https://user-images.githubusercontent.com/23134958/196102682-e2c29481-ec80-493c-ab9f-10991811893e.png">


The efast method doesn't work because you have some parameters with lower bounds == upper bounds, so the Uniform distribution errors when it's passed the bounds, you can modify your function as below to get it to work.

```
function run_sensitivity_analysis()
                  p_bounds = [[1.0e-14, 100000], [0.01, 500], [1, 500], [1.0e-8, 100]]
                  u0 = [1.6382099999999998e13, 3.4061512877350002e10, 0.0, 100000.0, 1.461e7]
                  p_fixed = [1000000000, 0, 0, 0, 0, 0,  882000.0, -1]
                  # Define a function that remakes the problem and gets its result
                  f1 = function (p)
                      pars = zeros(12); pars[4:9] = p_fixed[1:6]; pars[1:3] = p[1:3]; pars[10] = p[4]; pars[11:12] = p_fixed[7:8]
                      sol = solve_model(pars, u0)
                      # File analysis.txt contains written last(sol[1,:])

                      [last(sol[1,:] * 1e200)]  # This hacky solution to handle tiny (10^-300) values sucks.
                  end

                  # Run GSA
                  fast_result = GlobalSensitivity.gsa(f1, eFAST(), p_bounds, samples=2^14)  # Fails
                  #sobol_result = GlobalSensitivity.gsa(f1, Sobol(), p_bounds, Ei_estimator=:Sobol2007, samples=10000)
                  return (fast_result.ST[1,:], fast_result.S1[1,:])
              end
```

**Comment by Ge0rges** [comment]
Thank you for that information. As an aside, do you think my wacky solution to deal with very small values changes the outcome of the analysis? My understanding of the math is that it shouldn't.

**Comment by Ge0rges** [comment]
I will also add it would be cool if eFAST behaved like Sobol and returned 0 values instead. Unifies the interface a bit.

**Comment by ChrisRackauckas** [comment]
That's the plan, see https://github.com/SciML/GlobalSensitivity.jl/pull/83

**Comment by Vaibhavdixit02** [comment]
>As an aside, do you think my wacky solution to deal with very small values changes the outcome of the analysis?

It is definitely causing issues, the eFAST result for your model doesn't seem to match Sobol. I re-ran several other examples to be sure that there wasn't anything else that might be causing it but doesn't look like it. Tbh literature always suggests using parameters in [0,1] domain only for gsa, but that's often no possible practically so we allow using the values as it is. 

My suggestion for your model is 1. try to get the observed variables' scale reasonable, iiuc it looks like though your u0 is e10 scale the last time point give e-13!? 😅  2. If possible re-parameterise your model such the you pass parameters of somewhat similar scale and then do a factor multiplication inside your `f1` to scale them appropriately for the model

**Comment by Vaibhavdixit02** [comment]
>Also why do you have a copy() call only on p[4]?

Ignore that, #83 is ready, I'll merge and create a release within a couple of hours and you can just use the latest version to run the function as it is

**Comment by Vaibhavdixit02** [comment]
@Ge0rges you can use v2.1.2 now

**Comment by Ge0rges** [comment]
Nice! Thanks for the tips and improvement. I'll work on fixing the scales, though I wonder if the GSA algorithm could normalize the inputs to be within [0,1].

**Comment by Ge0rges** [comment]
@Vaibhavdixit02 updated to latest version, switched to eFAST, and weirdly I get nonzero values for identical bounds?

```
p_bounds = [[1.0e-14, 100000], [0.01, 500], [1, 500], [1000000000, 1000000000], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1.0e-8, 100], [882000.0, 882000.0], [-1, -1]]

f1 = function (p)
     sol = solve_model(p, u0)
    [last(sol[1, :]) * 1e200]
end

sobol_result = GlobalSensitivity.gsa(f1, eFAST(), p_bounds, samples=2^10)
return (sobol_result.ST[1,:], sobol_result.S1[1,:])
```

**Comment by Ge0rges** [comment]
Look at your commit and seems like your conditional if statement works to identify equal bounds...

```
for (j, v) in enumerate(p_bounds)
        if p_bounds[j][1] == p_bounds[j][2]
            @printf "same bounds: %s\n" v
        end
    end

    # Define a function that remakes the problem and gets its result
    f1 = function (p)
        sol = solve_model(p, u0)
        [last(sol[1, :]) * 1e200]
    end

    # Run GSA
    sobol_result = GlobalSensitivity.gsa(f1, eFAST(), p_bounds, samples=2^10)
    @printf "sobol T: %s\n" sobol_result.ST[1,:]
```

Output:
````
same bounds: Real[1000000000, 1000000000]
same bounds: Real[0, 0]
same bounds: Real[0, 0]
same bounds: Real[0, 0]
same bounds: Real[0, 0]
same bounds: Real[0, 0]
same bounds: Real[882000.0, 882000.0]
same bounds: Real[-1, -1]
sobol T: [0.8630413479272362, 0.8913392355004319, 0.8561012812442496, 0.8844354099002445, 0.863187985875788, 0.8653135861544157, 0.8859176270623108, 0.8659130475648313, 0.8078074792439602, 0.8924281370072416, 0.8309263086754832, 0.8829918924453956]
```

**Comment by Vaibhavdixit02** [comment]
Yes, I observed that, but it looks like an issue with your model. I tried the same case on simpler models it works correctly, I can take a look at the model tomorrow (IST) and get back to you with the changes I mentioned before.

**Comment by Ge0rges** [comment]
Huh, I'm puzzled as to why it should be model dependent... will continue looking at this today as well and try your tips. Thank you.

**Comment by Vaibhavdixit02** [comment]
So, it looks like the first observed variable (which you want to use for GSA), becomes 0 for almost all values of parameters except very close to the minimum of the bounds you are passing. That's the issue, so even with your hack of *1e200, the output of the function on which you are performing is always 0, hence you get equal sensitivity (quite high) for each variable. The discrepancy between sobol and eFAST can be understood by the difference in sampling used in the methods.

**Comment by Ge0rges** [comment]
Got it. Any recommendations as to how I could scale things to work? I thought of doing z-normalization with estimated min-max bounds, but despite this the numbers are too small. Perhaps if I normalize the values returned to GSA after all samples are run I could get tighter bounds.

**Comment by Vaibhavdixit02** [comment]
Why does that state go to 0, is it expected? Can you modify the time span or something else that would allow it to not go to 0, or perform GSA on another state?

**Comment by Ge0rges** [comment]
It is expected for that value to go to zero under a large combination of parameters, modifying it not go to 0 within the model would compromise its function. I could truncate it out of the GSA, though I was hoping to take it into account as a key variable in scenarios not displayed here where it fluctuates more often away from 0.

**Comment by Vaibhavdixit02** [comment]
I think I am not clear of what is the output of interest here, is it not only the first state at last time point? 

The returns mentioned below are for `f1` function

1. You can instead run GSA on the entire time span (so you'd return `sol[1,:]` instead of `last(sol[1,:])`)
2. If you are interested in the other state's sensitivities at the last time point also, you can return `sol[:, end]` 
3. if you are interested in all states' over the entire timespan then just return the solution `sol`

**Comment by Ge0rges** [comment]
The output of interest is the last time point of all the outputs. So the model outputs the variation of 4 variables, I'm looking at the just the last value of each.

**Comment by Vaibhavdixit02** [comment]
It would persist for the first state, yes, but having the other states would allow you something more meaningful. For the first state unless you can avoid the zero

**Comment by Ge0rges** [comment]
Thank you for all your help, that was a good catch! I will brainstorm a way to avoid this zero in the first state.

**Comment by Ge0rges** [comment]
So it seems like I need to normalize the first state. However my issue is that because I only solve one parameter set at a time, I don't have access to the bounds of that state across the samples. 

Is there a way I could either get GSA to give me all of the sample parameters to then return all the outputs in a matrix? Or, is there a way I can pass a normalization function to GSA for it to execute once all samples have been solved? 

I don't really see how I can scale my state without knowing its bounds. Even if I scaled the solution linearly, I would still get a large amplitude in the range (the theoretical solution range for this state is 1e-400 to 1e17).

**Comment by Vaibhavdixit02** [comment]
>Is there a way I could either get GSA to give me all of the sample parameters to then return all the outputs in a matrix?

Yes, you can use these lines https://github.com/SciML/GlobalSensitivity.jl/blob/be7d32c20e4d21866cacf69a7918ed0a5ee57e96/src/sobol_sensitivity.jl#L321-L326 to generate the required input design matrices and pass them with this method https://github.com/SciML/GlobalSensitivity.jl/blob/be7d32c20e4d21866cacf69a7918ed0a5ee57e96/src/sobol_sensitivity.jl#L109-L112. To scale the output you'd have to make it a part of the `f` function you define for GSA, you can indeed take a batch approach and do it at once for all outputs, like how this https://github.com/SciML/GlobalSensitivity.jl/blob/master/test/sobol_method.jl#L3-L6 is defined.

Take a look at https://docs.sciml.ai/GlobalSensitivity/stable/tutorials/parallelized_gsa/#Direct-Use-of-Design-Matrices and https://docs.sciml.ai/GlobalSensitivity/stable/tutorials/parallelized_gsa/#Parallelizing-the-Global-Sensitivity-Analysis as well as the test file for sobol linked above to get a good idea of how to get this done. It should definitely be possible with what we have in place.

**Comment by Ge0rges** [comment]
Thank you!

**Comment by Ge0rges** [comment]
Why does Sobol not require this scaling to work, but eFAST does?
